name: skip-core ci

on:
  push:
    branches: '*'
  schedule:
    - cron:  '0 * * * *'

jobs:
  skip-core-tests:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - run: brew install tree
      - uses: actions/checkout@v3
        path: skip-core
        repository: http://github.com/skiptools/skip-core.git
      - run: cd skip-core
      - run: scripts/buildtest.sh
      - uses: actions/checkout@v3
        path: skip
        repository: http://github.com/skiptools/skip.git
      - uses: actions/checkout@v3
        path: SkipSource
        repository: http://github.com/skiptools/SkipSource.git
        token: ${{ secrets.GH_TOKEN }}


