name: skip-core ci

on:
  push:
    branches: '*'
  schedule:
    - cron:  '0 * * * *'

jobs:
  skip-core-tests:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - run: brew install tree
      - uses: actions/checkout@v3
        with:
          path: skip-core
          repository: skiptools/skip-core
      - run: cd skip-core
      - run: scripts/buildtest.sh
      - uses: actions/checkout@v3
        with:
          path: skip
          repository: skiptools/skip
      - uses: actions/checkout@v3
        with:
          path: SkipSource
          repository: skiptools/SkipSource
          token: ${{ secrets.GH_TOKEN }}


