name: skip-core ci

on:
  push:
    branches: '*'
  schedule:
    - cron:  '0 * * * *'

jobs:
  skip-core-tests-external:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - name: Install tools
        run: brew install tree
      - name: Checkout skip-core
        uses: actions/checkout@v3
      - name: Check skiptool (release)
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info
      - name: Run skip-core tests (debug)
        run: scripts/buildtest.sh Debug
      - name: Run skip-core tests (release)
        run: scripts/buildtest.sh Release

  skip-core-tests-internal:
    runs-on: macos-12
    steps:
      - name: Install tools
        run: brew install tree
      - name: Checkout skip-core
        uses: actions/checkout@v3
        with:
          path: skip-core
          repository: skiptools/skip-core
      - name: Checkout skip
        uses: actions/checkout@v3
        with:
          path: skip
          repository: skiptools/skip
      - name: Checkout SkipSource
        uses: actions/checkout@v3
        with:
          path: SkipSource
          repository: skiptools/SkipSource
          token: ${{ secrets.GH_TOKEN }}
      - name: Check skiptool (debug)
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run skip-core tests (debug)
        run: scripts/buildtest.sh Debug
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run skip-core tests (release)
        run: scripts/buildtest.sh Release
        working-directory: skip-core
        env:
          SKIPLOCAL: ..


