name: skip-core ci

on:
  push:
    branches: 'main'
  schedule:
    - cron:  '0,6,12,18 * * * *'

env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer

jobs:
  skip-core-modules:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-12']
        #os: ['macos-12', 'macos-13']
        target: ['SkipLib', 'SkipFoundation', 'SkipDevice', 'SkipSQL', 'SkipUI', 'ExampleLib', 'ExampleApp' ]

    runs-on: ${{ matrix.os }}

    env:
      CONFIG: 'Debug'
      TARGET: ${{ matrix.target }}

    steps:
      - name: Checkout skip-core
        uses: actions/checkout@v3
        with:
          path: skip-core
          repository: skiptools/skip-core

      - name: Check skiptool (external)
        working-directory: skip-core
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info

      - name: Checkout skip
        uses: actions/checkout@v3
        with:
          path: skip
          repository: skiptools/skip

      - name: Checkout SkipSource
        uses: actions/checkout@v3
        with:
          path: SkipSource
          repository: skiptools/SkipSource
          token: ${{ secrets.GH_TOKEN }}

      - name: Check skiptool (local)
        working-directory: skip-core
        run: SKIPLOCAL=.. swift package --disable-sandbox --allow-writing-to-package-directory skip info

      - name: Run ${{ matrix.target }} macOS Swift Tests
        if: false
        working-directory: skip-core
        run: |
          SKIPLOCAL=.. xcodebuild test -skipPackagePluginValidation -configuration "${CONFIG}" -sdk "macosx" -destination "platform=macosx" -scheme "${{ matrix.target }}"

      # symbolgraph-extract needs to be manually run not because we use the symbols,
      # but because it pre-caches SwiftShims.swiftmodule and other modules into a
      # temporary folders that the transpiler build plug-in does not have write access to

      # this shows up as an error on the GH runners like:
      #
      # Error: terminated(1): /usr/bin/xcrun swift symbolgraph-extract -module-name SkipUnit -include-spi-symbols -skip-inherited-docs -skip-synthesized-members -output-dir /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/7D655714-40E7-4E36-B322-774B8ACBE4FB -target x86_64-apple-macosx12.0 -sdk /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -F /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/../../Library/Frameworks/ -minimum-access-level internal -I /Users/runner/Library/Developer/Xcode/DerivedData/skip-core-cpmrmpnysoyybacpdfaabaxuqhex/Build/Products/Debug output:
      #
      # <unknown>:0: error: unable to open output file '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/clang/ModuleCache/1CUWPUEC7D78B/Darwin-1IPQPNED63C6S.pcm': 'Operation not permitted'
      #
      # <unknown>:0: error: could not build Objective-C module 'Darwin'
      #
      # <unknown>:0: error: unable to open output file '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/clang/ModuleCache/28ISCAFRG14KL/XCTest-3BBK7W05KE09V.pcm': 'Operation not permitted'
      #
      # /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/XCTest.swiftmodule/x86_64-apple-macos.swiftinterface:7:19: error: could not build Objective-C module 'XCTest'
      #
      # @_exported import XCTest

      - name: Cache Swift modules
        working-directory: skip-core
        run: |
          mkdir ${TMPDIR}/symbolgraph-extract
          for module in SwiftShims Foundation Darwin XCTest OSLog os CoreTransferable SwiftUI ; do /usr/bin/xcrun swift symbolgraph-extract -module-name ${module} -include-spi-symbols -skip-inherited-docs -skip-synthesized-members -output-dir ${TMPDIR}/symbolgraph-extract -target x86_64-apple-macosx12.0 -sdk ${DEVELOPER_DIR}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -F ${DEVELOPER_DIR}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/../../Library/Frameworks/ -minimum-access-level internal -I .build/debug/ ; done
          ls -lah ${TMPDIR}/symbolgraph-extract

      - name: Run ${{ matrix.target }} macOS Kotlin Tests
        working-directory: skip-core
        run: |
          SKIPLOCAL=.. xcodebuild test -skipPackagePluginValidation -configuration "${CONFIG}" -sdk "macosx" -destination "platform=macosx" -scheme "${{ matrix.target }}Kotlin"

      - name: Run ${{ matrix.target }} iOS Swift Tests
        working-directory: skip-core
        run: |
          SKIPLOCAL=.. xcodebuild test -skipPackagePluginValidation -configuration "${CONFIG}" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone SE (3rd generation)" -scheme "${{ matrix.target }}"

      - name: Run ${{ matrix.target }} Gradle Tests
        working-directory: skip-core
        run: |
          # get the most recent derived data folder
          DER=`ls -1rtd ~/Library/Developer/Xcode/DerivedData/skip-core-*/SourcePackages/plugins/skip-core.output | tail -n 1`

          #tree -lh -I build ${DER}/${{ matrix.target }}KotlinTests/SkipTranspilePlugIn/

          # run the tests for the target
          # cd ${DER}/${{ matrix.target }}KotlinTests/SkipTranspilePlugIn
          gradle --project-dir ${DER}/${{ matrix.target }}KotlinTests/SkipTranspilePlugIn check


  skip-core-tests-external:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - name: Install tools
        run: brew install tree
      - name: Checkout skip-core
        uses: actions/checkout@v3
      - name: Check skiptool (release)
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info

      - name: Build skip-core
        run: swift build

      - name: Pre-cache Swift modules
        run: |
          mkdir ${TMPDIR}/symbolgraph-extract
          for module in SkipLib SkipFoundation Darwin XCTest OSLog os ; do /usr/bin/xcrun swift symbolgraph-extract -module-name ${module} -include-spi-symbols -skip-inherited-docs -skip-synthesized-members -output-dir ${TMPDIR}/symbolgraph-extract -target x86_64-apple-macosx12.0 -sdk ${DEVELOPER_DIR}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -F ${DEVELOPER_DIR}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/../../Library/Frameworks/ -minimum-access-level internal -I .build/debug/ ; done
          ls -la ${TMPDIR}/symbolgraph-extract

      - name: Run SkipLib tests (debug)
        run: scripts/buildtest.sh Debug SkipLib

      - name: Run SkipFoundation tests (debug)
        run: scripts/buildtest.sh Debug SkipFoundation

      - name: Run SkipDevice tests (debug)
        run: scripts/buildtest.sh Debug SkipDevice

      - name: Run SkipSQL tests (debug)
        run: scripts/buildtest.sh Debug SkipSQL

      - name: Run SkipUI tests (debug)
        run: scripts/buildtest.sh Debug SkipUI

      - name: Run ExampleLib tests (debug)
        run: scripts/buildtest.sh Debug ExampleLib

      - name: Run ExampleApp tests (debug)
        run: scripts/buildtest.sh Debug ExampleApp


  skip-core-tests-internal:
    if: false
    runs-on: macos-12
    steps:
      - name: Install tools
        run: brew install tree
      - name: Checkout skip-core
        uses: actions/checkout@v3
        with:
          path: skip-core
          repository: skiptools/skip-core
      - name: Checkout skip
        uses: actions/checkout@v3
        with:
          path: skip
          repository: skiptools/skip
      - name: Checkout SkipSource
        uses: actions/checkout@v3
        with:
          path: SkipSource
          repository: skiptools/SkipSource
          token: ${{ secrets.GH_TOKEN }}
      - name: Check skiptool (debug)
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipLib tests (debug)
        run: scripts/buildtest.sh Debug SkipLib
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipFoundation tests (debug)
        run: scripts/buildtest.sh Debug SkipFoundation
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipDevice tests (debug)
        run: scripts/buildtest.sh Debug SkipDevice
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipSQL tests (debug)
        run: scripts/buildtest.sh Debug SkipSQL
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipUI tests (debug)
        run: scripts/buildtest.sh Debug SkipUI
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run ExampleLib tests (debug)
        run: scripts/buildtest.sh Debug ExampleLib
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run ExampleApp tests (debug)
        run: scripts/buildtest.sh Debug ExampleApp
        working-directory: skip-core
        env:
          SKIPLOCAL: ..


