name: skip-core ci

on:
  push:
    branches: '*'
  schedule:
    - cron:  '0,6,12,18 * * * *'

jobs:
  skip-core-tests-external:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - name: Install tools
        run: brew install tree
      - name: Checkout skip-core
        uses: actions/checkout@v3
      - name: Check skiptool (release)
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info

      - name: Build skip-core
        run: swift build

      # symbolgraph-extract needs to be manually run not because we use the symbols,
      # but because it pre-caches SwiftShims.swiftmodule and other modules into a
      # temporary folders that the transpiler build plug-in does not have write access to

      # this shows up as an error on the GH runners like:
      #
      # Error: terminated(1): /usr/bin/xcrun swift symbolgraph-extract -module-name SkipUnit -include-spi-symbols -skip-inherited-docs -skip-synthesized-members -output-dir /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/7D655714-40E7-4E36-B322-774B8ACBE4FB -target x86_64-apple-macosx12.0 -sdk /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -F /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/../../Library/Frameworks/ -minimum-access-level internal -I /Users/runner/Library/Developer/Xcode/DerivedData/skip-core-cpmrmpnysoyybacpdfaabaxuqhex/Build/Products/Debug output:
      #
      # <unknown>:0: error: unable to open output file '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/clang/ModuleCache/1CUWPUEC7D78B/Darwin-1IPQPNED63C6S.pcm': 'Operation not permitted'
      #
      # <unknown>:0: error: could not build Objective-C module 'Darwin'
      #
      # <unknown>:0: error: unable to open output file '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/C/clang/ModuleCache/28ISCAFRG14KL/XCTest-3BBK7W05KE09V.pcm': 'Operation not permitted'
      #
      # /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/XCTest.swiftmodule/x86_64-apple-macos.swiftinterface:7:19: error: could not build Objective-C module 'XCTest'
      #
      # @_exported import XCTest

      - name: Pre-cache Swift modules
        run: for module in SkipLib SkipFoundation Darwin XCTest OSLog os ; do /usr/bin/xcrun swift symbolgraph-extract -module-name ${module} -include-spi-symbols -skip-inherited-docs -skip-synthesized-members -output-dir $TMPDIR -target x86_64-apple-macosx12.0 -sdk /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -F /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/../../Library/Frameworks/ -minimum-access-level internal -I .build/debug/ ; done

      - name: Run SkipLib tests (debug)
        run: scripts/buildtest.sh Debug SkipLib

      - name: Run SkipFoundation tests (debug)
        run: scripts/buildtest.sh Debug SkipFoundation

      - name: Run SkipDevice tests (debug)
        run: scripts/buildtest.sh Debug SkipDevice

      - name: Run SkipSQL tests (debug)
        run: scripts/buildtest.sh Debug SkipSQL

      - name: Run SkipUI tests (debug)
        run: scripts/buildtest.sh Debug SkipUI

      - name: Run ExampleLib tests (debug)
        run: scripts/buildtest.sh Debug ExampleLib

      - name: Run ExampleApp tests (debug)
        run: scripts/buildtest.sh Debug ExampleApp


  skip-core-tests-internal:
    if: false
    runs-on: macos-12
    steps:
      - name: Install tools
        run: brew install tree
      - name: Checkout skip-core
        uses: actions/checkout@v3
        with:
          path: skip-core
          repository: skiptools/skip-core
      - name: Checkout skip
        uses: actions/checkout@v3
        with:
          path: skip
          repository: skiptools/skip
      - name: Checkout SkipSource
        uses: actions/checkout@v3
        with:
          path: SkipSource
          repository: skiptools/SkipSource
          token: ${{ secrets.GH_TOKEN }}
      - name: Check skiptool (debug)
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipLib tests (debug)
        run: scripts/buildtest.sh Debug SkipLib
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipFoundation tests (debug)
        run: scripts/buildtest.sh Debug SkipFoundation
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipDevice tests (debug)
        run: scripts/buildtest.sh Debug SkipDevice
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipSQL tests (debug)
        run: scripts/buildtest.sh Debug SkipSQL
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipUI tests (debug)
        run: scripts/buildtest.sh Debug SkipUI
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run ExampleLib tests (debug)
        run: scripts/buildtest.sh Debug ExampleLib
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run ExampleApp tests (debug)
        run: scripts/buildtest.sh Debug ExampleApp
        working-directory: skip-core
        env:
          SKIPLOCAL: ..


