name: skip-core ci

on:
  push:
    branches: '*'
  schedule:
    - cron:  '0 * * * *'

jobs:
  skip-core-tests-external:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - name: Install tools
        run: brew install tree
      - name: Checkout skip-core
        uses: actions/checkout@v3
      - name: Check skiptool (release)
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info
      - name: Run SkipLib tests (debug)
        run: scripts/buildtest.sh Debug SkipLib
      - name: Run SkipFoundation tests (debug)
        run: scripts/buildtest.sh Debug SkipFoundation
      - name: Run SkipUI tests (debug)
        run: scripts/buildtest.sh Debug SkipUI
      - name: Run ExampleLib tests (debug)
        run: scripts/buildtest.sh Debug ExampleLib
      - name: Run ExampleApp tests (debug)
        run: scripts/buildtest.sh Debug ExampleApp

  skip-core-tests-internal:
    runs-on: macos-12
    steps:
      - name: Install tools
        run: brew install tree
      - name: Checkout skip-core
        uses: actions/checkout@v3
        with:
          path: skip-core
          repository: skiptools/skip-core
      - name: Checkout skip
        uses: actions/checkout@v3
        with:
          path: skip
          repository: skiptools/skip
      - name: Checkout SkipSource
        uses: actions/checkout@v3
        with:
          path: SkipSource
          repository: skiptools/SkipSource
          token: ${{ secrets.GH_TOKEN }}
      - name: Check skiptool (debug)
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipLib tests (debug)
        run: scripts/buildtest.sh Debug SkipLib
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipFoundation tests (debug)
        run: scripts/buildtest.sh Debug SkipFoundation
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipUI tests (debug)
        run: scripts/buildtest.sh Debug SkipUI
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run ExampleLib tests (debug)
        run: scripts/buildtest.sh Debug ExampleLib
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run ExampleApp tests (debug)
        run: scripts/buildtest.sh Debug ExampleApp
        working-directory: skip-core
        env:
          SKIPLOCAL: ..


