name: skip-core ci

on:
  push:
    branches: '*'
  schedule:
    - cron:  '0 * * * *'

jobs:
  skip-core-tests-external:
    # needs: https://github.com/actions/runner-images/issues/6426
    #runs-on: macos-13
    runs-on: macos-12
    steps:
      - name: Install tools
        run: brew install tree
      - name: Checkout skip-core
        uses: actions/checkout@v3
      - name: Check skiptool (release)
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info

      - name: Build SkipLib
        run: swift build

      # symbolgraph-extract needs to be manually run not because we use the symbols,
      # but because it pre-caches SwiftShims.swiftmodule and other modules into a
      # temporary folders that the transpiler build plug-in does not have write access to
      - name: Pre-cache SkipLib symbols
        run: /usr/bin/xcrun swift symbolgraph-extract -module-name SkipLib -include-spi-symbols -skip-inherited-docs -skip-synthesized-members -output-dir $TMPDIR -target x86_64-apple-macosx12.0 -sdk /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -F /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/../../Library/Frameworks/ -minimum-access-level internal -I .build/debug/

      - name: Run SkipLib tests (debug)
        run: scripts/buildtest.sh Debug SkipLib

      - name: Run SkipFoundation tests (debug)
        if: false
        run: scripts/buildtest.sh Debug SkipFoundation
      - name: Run SkipDevice tests (debug)
        if: false
        run: scripts/buildtest.sh Debug SkipDevice
      - name: Run SkipSQL tests (debug)
        if: false
        run: scripts/buildtest.sh Debug SkipSQL
      - name: Run SkipUI tests (debug)
        if: false
        run: scripts/buildtest.sh Debug SkipUI
      - name: Run ExampleLib tests (debug)
        if: false
        run: scripts/buildtest.sh Debug ExampleLib
      - name: Run ExampleApp tests (debug)
        if: false
        run: scripts/buildtest.sh Debug ExampleApp

  skip-core-tests-internal:
    if: false
    runs-on: macos-12
    steps:
      - name: Install tools
        run: brew install tree
      - name: Checkout skip-core
        uses: actions/checkout@v3
        with:
          path: skip-core
          repository: skiptools/skip-core
      - name: Checkout skip
        uses: actions/checkout@v3
        with:
          path: skip
          repository: skiptools/skip
      - name: Checkout SkipSource
        uses: actions/checkout@v3
        with:
          path: SkipSource
          repository: skiptools/SkipSource
          token: ${{ secrets.GH_TOKEN }}
      - name: Check skiptool (debug)
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipLib tests (debug)
        run: scripts/buildtest.sh Debug SkipLib
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipFoundation tests (debug)
        run: scripts/buildtest.sh Debug SkipFoundation
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipDevice tests (debug)
        run: scripts/buildtest.sh Debug SkipDevice
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipSQL tests (debug)
        run: scripts/buildtest.sh Debug SkipSQL
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run SkipUI tests (debug)
        run: scripts/buildtest.sh Debug SkipUI
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run ExampleLib tests (debug)
        run: scripts/buildtest.sh Debug ExampleLib
        working-directory: skip-core
        env:
          SKIPLOCAL: ..
      - name: Run ExampleApp tests (debug)
        run: scripts/buildtest.sh Debug ExampleApp
        working-directory: skip-core
        env:
          SKIPLOCAL: ..


